Drop gcc:sid:amd64 jobs
They fail to build with GCC 15.2.0:

    rdata/in_1/wks_11.c: In function 'totext_in_wks':
    rdata/in_1/wks_11.c:238:77: error: '%u' directive output may be truncated writing between 1 and 10 bytes into a region of size 6 [-Werror=format-truncation=]
      238 |                                                 snprintf(buf, sizeof(buf), "%u",
          |                                                                             ^~
    rdata/in_1/wks_11.c:238:76: note: directive argument in the range [1, 4294967295]
      238 |                                                 snprintf(buf, sizeof(buf), "%u",
          |                                                                            ^~~~
    rdata/in_1/wks_11.c:238:49: note: 'snprintf' output between 2 and 11 bytes into a destination of size 6
      238 |                                                 snprintf(buf, sizeof(buf), "%u",
          |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      239 |                                                          i * 8 + j);
          |                                                          ~~~~~~~~~~

nolibtool:sid:amd64 keeps building, so keep it.

Move -O3 and --without-lmdb to gcc:noble:amd64.

Move RUN_MAKE_INSTALL=1 to gcc:trixie:amd64 as Sphinx is needed to build
man pages that are checked for in util/check-make-install.